### ISSUE TITLE
Pandas tutorial lab

### ISSUE THREAD

**Issue by insertinterestingnamehere** [byuimpact/numerical_computing#538]
Since we are trying to give our students a basic background in data analysis, it would make a lot of sense to introduce them to some of the basic functionality of Pandas. As I understand it, if you want to use NumPy-like functionality with a variety of data types and use named columns and rows, Pandas is the way to go.

**Comment by ayr0** [comment]
There is now a pandas lab
https://github.com/byuimpact/numerical_computing/pull/621

**Comment by shanemcq18** [comment]
Update: there are now _three_ Pandas labs (boom!)
